server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://movemate-db.czgeuuoi06xx.eu-north-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: db12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  region: eu-north-1
  s3:
    bucket: traffic-event-images
    folder: images/

cognito:
  userPoolId: <?? Cognito user pool ID>
  clientId: <???? app client ID>
  region: eu-west-1


